Feature/us 020 put operation update a user
at-internship/at-sce-api pull request #15
Opened 2021-03-11 20:18 UTC by ATdllerenas

Implementation of the update operation for users.

2021-03-11 20:35 UTC, luisgalindoluna requested changes
Please solve conflicts first

2021-03-12 00:06 UTC, luisgalindoluna requested changes
Overall looks good, just use your mapper for your updateUser method

2021-03-12 00:06 UTC, luisgalindoluna commented on src/main/java/com/agilethought/atsceapi/service/UserServiceImpl.java
> +			response.setStatus(user.getStatus());
Your mapper already does this

2021-03-12 01:50 UTC, ivanflores15 commented on src/main/java/com/agilethought/atsceapi/dto/UpdateUserResponse.java
> +	private String password;
I think password must not be included as por of response. What do you think @EmiliaGuillen-dev?

2021-03-12 04:35 UTC, EmiliaGuillen-dev commented on src/main/java/com/agilethought/atsceapi/dto/UpdateUserResponse.java
> +	private String password;
I totally agree

2021-03-12 19:17 UTC, ATdllerenas commented on src/main/java/com/agilethought/atsceapi/dto/UpdateUserResponse.java
> +	private String password;
So is the only change missing? I will make de change.

2021-03-12 23:17 UTC, luisgalindoluna approved these changes
Well done

2021-03-12 23:26 UTC, ivanflores15 approved these changes
looks good

2021-03-12 23:26 UTC, ivanflores15 commented on src/main/java/com/agilethought/atsceapi/service/UserServiceImpl.java
> +			throw new NotFoundException("User Not Found with id: " + Id);
Just as recommendation, it is a good practice have a constant class, where we define constant messegas such as `private static final String USER_NOT_FOUND =  "User Not Found with id: %s`.

2021-03-12 23:42 UTC, EmiliaGuillen-dev approved these changes
looks good

2021-03-12 23:45 UTC, merged