Move out JaCoCo plugin from profiles tags
at-internship/at-sce-api pull request #37
Opened 2021-04-09 17:28 UTC by RamOwen99

The JaCoCo plugin was inside from the profiles tag instead of the main
plugins tag, because all the profiles need to use JaCoCo

2021-04-12 16:18 UTC, luisgalindoluna approved these changes
Looks good

2021-04-12 16:33 UTC, ivanflores15 requested changes

2021-04-12 16:33 UTC, ivanflores15 commented on src/test/java/com/agilethought/atsceapi/service/UserServiceImplTest.java
> +    private MapperFacade userRepositoryMapper;
name of attribue it not matching with  type object. It does not make sense.

2021-04-12 16:33 UTC, ivanflores15 commented on src/test/java/com/agilethought/atsceapi/service/UserServiceImplTest.java
> +    public void itShouldGetAllUsers(){
I prefer left previous name

2021-04-12 17:14 UTC, ivanflores15 commented
your build is still having issue, and pipeline say no tests were run. It's something related to maven-surefire-plugin:2.22.2:test. we expected at least one test was run. 
![image](https://user-images.githubusercontent.com/73487119/114434297-74a8a900-9b88-11eb-8d4b-022f81237f68.png)

2021-04-12 22:17 UTC, ivanflores15 requested changes

2021-04-12 22:17 UTC, ivanflores15 commented on src/test/java/com/agilethought/atsceapi/service/UserServiceImplTest.java
> +import static org.junit.Assert.*;
it is not recommended include all packages inside of library. just import packages that are used

2021-04-13 13:18 UTC, ivanflores15 approved these changes
good job

2021-04-13 16:12 UTC, EmiliaGuillen-dev approved these changes
looks good

2021-04-13 16:13 UTC, merged