Feature/us 40 nfr create junits for history flow
at-internship/at-sce-api pull request #45
Opened 2021-04-26 20:21 UTC by JavierMotaAT

2021-04-26 20:26 UTC, EmiliaGuillen-dev approved these changes
looks good

2021-04-26 23:00 UTC, ivanflores15 requested changes

2021-04-26 23:00 UTC, ivanflores15 commented on src/test/java/com/agilethought/atsceapi/service/HistoryServiceImplTest.java
> +		FixedExpenses fixedExpenses = new FixedExpenses();
You are repeating code inside HistoryValidatorTest.class. I think is a better way create a dummy factory class in orden to get instances of NewHistoryRequest

2021-04-26 23:00 UTC, ivanflores15 commented on src/test/java/com/agilethought/atsceapi/validator/history/HistoryValidatorTest.java
> +	public void populateHistoryRequest() {
Put it inside of dummy factory class

2021-04-26 23:04 UTC, VictorMunguia approved these changes

2021-04-26 23:26 UTC, ivanflores15 requested changes

2021-04-26 23:26 UTC, ivanflores15 commented on src/test/java/com/agilethought/atsceapi/validator/history/HistoryValidatorTest.java
> +			Assertions.assertEquals("One or more fields are invalid", errorMessageException.getMessage());
You are using a lot times "One or more fields are invalid", convert to constant or use constant defined in constant class

2021-04-27 17:16 UTC, luisgalindoluna approved these changes
Great

2021-04-27 22:16 UTC, ivanflores15 approved these changes

2021-04-27 22:16 UTC, merged