Implementation HealthCheck
at-internship/at-sce-api pull request #48
Opened 2021-05-12 18:03 UTC by blancaagc

2021-05-14 03:28 UTC, ivanflores15 requested changes

2021-05-14 03:28 UTC, ivanflores15 commented on pom.xml
> +					<groupId>com.heroku.sdk</groupId>
you added an unnecesarry tab, please rollback this.

2021-05-14 14:12 UTC, luisgalindoluna approved these changes
Looks fine, aside from the unnecessary tab in the pom.

2021-05-18 22:31 UTC, ivanflores15 approved these changes

2021-05-19 21:38 UTC, EmiliaGuillen-dev approved these changes
looks good

2021-05-26 18:09 UTC, merged