Feature/us 018 post operation new user
at-internship/at-sce-api pull request #6
Opened 2021-02-26 19:27 UTC by AlejandraBC

2021-02-26 21:06 UTC, ivanflores15 requested changes
looks good once you change this. thank you.

2021-02-26 21:06 UTC, ivanflores15 commented on src/main/java/com/agilethought/atsceapi/controller/UserController.java
> +	@PostMapping(value = "/at-sce-api/api/v1/users", consumes = "application/json", produces = "application/json")
move this as a parameter of base path API into `@RequestMapping` anotation below `@RestController` annotation
keep `/users` as part of `@PostMapping`

2021-02-26 21:06 UTC, ivanflores15 commented on src/main/java/com/agilethought/atsceapi/domain/CreateUserRequest.java
> +public class CreateUserRequest {
Name of class should be _nouns_ and don't include _verbs_ ("Create")

2021-02-26 21:06 UTC, ivanflores15 commented on src/main/java/com/agilethought/atsceapi/domain/CreateUserResponse.java
> +public class CreateUserResponse {
Name class should be nouns

2021-03-01 22:28 UTC, luisgalindoluna requested changes
Did you forget to merge from develop into your branch? 
Your controller, repo, service and serviceImpl are missing several methods that should be in there

2021-03-01 22:30 UTC, closed without merging