Implementation Get Operation to Obtain An User With Given Id
at-internship/at-sce-api pull request #8
Opened 2021-03-01 17:26 UTC by blancaagc

I added a functionality to obtain an user with an ID and return an error when the ID is wrong.

2021-03-01 18:21 UTC, luisgalindoluna approved these changes
Looks good to me

2021-03-01 18:48 UTC, ivanflores15 requested changes

2021-03-01 18:48 UTC, ivanflores15 commented on src/main/java/com/agilethought/atsceapi/model/User.java
> +import javax.persistence.GeneratedValue;
your project is broken, please fix it. 
![image](https://user-images.githubusercontent.com/73487119/109543846-6f861380-7a8c-11eb-9ac2-7869d3ea1b3f.png)

2021-03-01 18:53 UTC, ivanflores15 requested changes
your project is broken, please fix it. 
![image](https://user-images.githubusercontent.com/73487119/109543846-6f861380-7a8c-11eb-9ac2-7869d3ea1b3f.png)

2021-03-01 19:11 UTC, ivanflores15 commented
Actually, your are  one commit behind delevop. To solve, this issue... 

- pull all to your delelop local branch
- merge your feature branch into develop local branch
- Solve conflicts
- Commit and push your changes

![image](https://user-images.githubusercontent.com/73487119/109546273-92fe8d80-7a8f-11eb-951d-e45ab91f23b3.png)

2021-03-02 15:10 UTC, ivanflores15 requested changes
![image](https://user-images.githubusercontent.com/73487119/109668593-eed02180-7b36-11eb-81c9-5ef3d5b71b27.png)

you removed your method to find users by Id. In that way your code doesn't do what is supposed

2021-03-02 18:37 UTC, ivanflores15 approved these changes
looks good for me

2021-03-02 18:38 UTC, luisgalindoluna approved these changes
Looks fine, good work.

2021-03-02 18:48 UTC, EmiliaGuillen-dev approved these changes
looks good 👍

2021-03-02 18:52 UTC, merged